### ISSUE TITLE
Default Player?

### ISSUE THREAD

**Issue by vincent404** [cosmicradiotv/podcast-plugin#10]
Though I think we should have a way just to output the correct episode file to a view, I think because this is intended to go out for public consumption that we should also include a default player (unless OctoberCMS includes one). Thoughts?

**Comment by blendermf** [comment]
I definitely think we should have a player. We'd probably have a component that's used to output it, and that's what any theme/site what use to display the player. October does not come with a player (because I'm used to it I'm tempted to just include mediaelement.js

**Comment by blendermf** [comment]
Started implementing this in 36ffd6a

**Comment by blendermf** [comment]
As of 9352877 this pretty much fully functional. May add more options later. Need to document and localize (sidenote, purely because of the code I'm using to parse youtube urls, I could modify the site to support vimeo embeds real easily. Will need to add on to that if we want to support anything else)

**Comment by vincent404** [comment]
Cool. If you feel the issue is resolved, close away @blendermf.

**Comment by blendermf** [comment]
I'm going to wait until I finish all the documentation and localization, but yeah.

**Comment by blendermf** [comment]
Closing this as of 1c562b1. The player is there, but now it's part of a bigger issue which is adding components for all the different kind of data, and lists of data we want to provide, so I'll add new issues for that.
