### ISSUE TITLE
No current way to access the episode title inside a page

### ISSUE THREAD

**Issue by blendermf** [cosmicradiotv/podcast-plugin#17]
So right now if you have an episode page that is used to display an episode, you can't set the title of that page to the name of the episode (or some combination of things from the episode / show).

As an example the way the post component in the blog plugin (https://github.com/cosmicradiotv/podcast-plugin/blob/master/components/Episode.php) does it is it sets the post as a page var along with setting the class member.

``` php
$this->post = $this->page['post'] = $this->loadPost()
```

and then on the page it uses this snippet of code in the php section

``` php
function onEnd()
{
    // Optional - set the page title to the post title
    if (isset($this->post))
        $this->page->title = $this->post->title;
}
```

It might make sense to make both the episode and show available in this manner (so you could for example make the title 'Show Name - Episode Title')

**Comment by vincent404** [comment]
I'd probably say make it a separate option or just some sort of method to
access any of the info (title, show name, etc)
