### ISSUE TITLE
Latest episode component (and shared Episode partials)

### ISSUE THREAD

**Issue by blendermf** [cosmicradiotv/podcast-plugin#18]
Currently displaying the latest episode by itself (or just the player) requires an extra query to get the show slug and episode slug of the latest episode, before the component itself then does another query for that same episode. It might be a good idea to add a component that just pulls the latest episode(either the latest by show[if a slug is provided] or latest from any show).

This will require making the episode partials shared.

**Comment by vincent404** [comment]
Can this be a method within the component or some sort of option. I'm
assuming you can put private methods within the component to make the code
cleaner.

**Comment by blendermf** [comment]
Really it'd have to be a component property so it's accessible from the cms.

But it doesn't matter, I am just realizing the reason I didn't want a new component is because then I'd have multiple partials that were identical, but I just noticed that you can have shared partials, so I'm just going to make a new component, and make the episode partials shared.

**Comment by t2t2** [comment]
Possibly could be fulfilled by an episodes component with perPage = 1, and then accessing the component's episodes list from page, would have a bug here where the pagination would clash

**Comment by blendermf** [comment]
That is true, but I specifically wanted/needed the player too, which has the sorting logic for releases and a separate variable for that, etc. I had originally started implementing it the way you mentioned, but I didn't want to have to rewrite an almost identical partial to support the Episodes component instead. This isn't to say it wouldn't be possible to change how the Episodes component works so it supports that. I did just commit a latest episode component, but if you want to change that it's fine.

**Comment by blendermf** [comment]
I'm going to mark this as closed for now (as of c8f3514) , if we want to change this later we can reopen this.
