### ISSUE TITLE
Allow manual sorting of release types

### ISSUE THREAD

**Issue by blendermf** [cosmicradiotv/podcast-plugin#19]
Currently the episode player component uses a set hardcoded ordering for release types, it would be nice if we could set a display priority for each release type so these could be sorted in whatever order the user likes.

**Comment by vincent404** [comment]
Or even have it sort of sortable on the fly from the view. Obviously this
could be queried for that, but yeah. Interesting idea.

**Comment by blendermf** [comment]
That's theoretically possible, but unless I'm mistaken October doesn't support any kind of reordering like that currently in its backend ui by default, so we'd have to add that feature ourselves, which is fine but that can be dealt with later (there is a trait you can use that is for ordered models that is part of October, it just doesn't display it nicely on the backend interface, but I'll use that in case they end up adding that). The rain lab pages plugin does have drag and drop ordering, so I can see what they did there when I get to that.

I should say most of that is based on what I've read in forum posts about the topic so things could have changed (for all I know it might work with the trait). It might also be easier to implement that ourselves than I'm thinking. But right now I really just need to be able to reorder things even if it's not the most intuitive.
