### ISSUE TITLE
Change component names to eliminate possible conflicts

### ISSUE THREAD

**Issue by t2t2** [cosmicradiotv/podcast-plugin#22]
Now octobercms has [ways to avoid conflicts](https://octobercms.com/docs/cms/components#aliases), but it might be better to have to have it in `podcastThing` format. Examples from others:
- [Blog - `blogThing`](https://github.com/rainlab/blog-plugin/blob/master/Plugin.php#L26-28)
- [Demo plugin - `demoThing`](https://github.com/octobercms/october/blob/master/plugins/october/demo/Plugin.php#L25)

(No conflicts probably yet, but Feed can easily become a conflict)

Also if we're changing names (which better happen early like this), I would suggest changing classes names themselves to `ThingComponent`.
- \+ Avoids conflicts with models (Episode)
- \+ More laravelish (eg. [Controllers](https://github.com/laravel/laravel/tree/master/app/Http/Controllers), [Providers](https://github.com/laravel/laravel/tree/master/app/Providers) or [Seeders](https://github.com/laravel/laravel/blob/master/database/seeds/DatabaseSeeder.php))
- \+ The `Component` suffix will be masked behind the alias for most people anyway.
- \- Not [reccomended in documentation](https://octobercms.com/docs/plugin/components)
  - ? Notably `Controller` (which are also reccomended to be suffix-less) is a [reccomended class prefix/suffix](https://octobercms.com/docs/help/developer-guide#class-naming), honestly surprised `ThingController` isn't used (see laravel-ish point)

**Comment by vincent404** [comment]
I definitely agree in on this to avoid potential conflicts, but to also
make the code more readable. Seems like following the format would make the
code a bit self documenting and pretty clean.

**Comment by blendermf** [comment]
Just read through everything linked there, and I'm cool with those changes. I also get the sense that while they recommend certain naming schemes at certain places they don't seem to be too sure about it themselves anyways (or worried about it). That naming scheme makes sense though, and I like it
