### ISSUE TITLE
Plugin Name Podcast

### ISSUE THREAD

**Issue by vincent404** [cosmicradiotv/podcast-plugin#3]
So a plugin named Podcast exists (http://octobercms.com/plugin/bubblecore-podcast). Literally posted yesterday. I'm thinking we name the plugin podcast-network or something similar. I'll take any suggestions. There plugin does cost a little bit of money, so I don't know their repo name. We could also go  u62-podcast-plugin

**Comment by t2t2** [comment]
I'm still gonna say it will probably not be a problem, as noted in url structure `bubblecore-podcast`, it will be `cosmicradiotv-podcast`. Similar to how [composer packages work](https://packagist.org/search/?q=admin)

**Comment by blendermf** [comment]
The only issue is that if we ever put the plugin up on the october marketplace they'd both have the same name displayed in big letters (granted, the author is listed right beside it although smaller). idk, it may still not be an issue with ours being free vs their paid one.

**Comment by t2t2** [comment]
Competition
- Signed, Europe

**Comment by vincent404** [comment]
Yeah. Might only be an issue on the namespace level or whatever. Not sure what name we are using there. 

-------Roberto J Villegas

**Comment by blendermf** [comment]
Anywhere we use a namespace it includes the author name and the plugin name so there shouldn't be conflicts.

(and I can tell you from working on localization that typing cosmicradiotv.podcast::lang. everywhere is driving me nuts [obviously I got to the point when that was all I was doing, and was just pasting that instead])

**Comment by vincent404** [comment]
Alright. We'll keep the name as such. Closing issue.
