### ISSUE TITLE
Generate RSS Feeds per Show-release Type

### ISSUE THREAD

**Issue by vincent404** [cosmicradiotv/podcast-plugin#4]
Generate RSS feeds for each show specific to release type. Make sure the RSS follows the iTunes specific RSS tags : https://www.apple.com/itunes/podcasts/specs.html in conjunction with any other RSS standard tags (http://www.rssboard.org/rss-profile). This can be validated here http://castfeedvalidator.com. To help lessen potential server load, we should probably cache the feed output as it won't change until a new episode is released. Not exactly sure how to achieve this, but definitely cache the db calls if at all possible.

**Comment by blendermf** [comment]
To be a little more descriptive, we need to support extra data for feeds like author, category (which can be multiple categories, and there are also subcategories to support), explicit tags, owner, etc.

Some of these will apply to shows, some to episodes (as shown in the chart on the itunes spec page). We should probably support some plugin settings for defaults, so you could set them for the whole network, and only change those if you have to on the specific show / episode.

**Comment by t2t2** [comment]
Probably done dc208ffdf0ca6682c1df143c9bfa62f536c8342d

**Comment by vincent404** [comment]
If possible, test the output from the component against http://castfeedvalidator.com/. If it validates and has no errors, we can close this.

**Comment by t2t2** [comment]
No errors, added some code to get rid of the warnings too
