### ISSUE TITLE
Determine File Size per Episode/Release type

### ISSUE THREAD

**Issue by vincent404** [cosmicradiotv/podcast-plugin#7]
This is a requirement for the enclosure tag in RSS 2.0.x (http://www.rssboard.org/rss-profile#element-channel-item-enclosure). This should be configured to auto detected when the URL is linked. This would not apply to any online video services (youtube, dailymotion, etc) that doesn't give a known file type.

**Comment by blendermf** [comment]
This should be relatively easy by requesting the header for the media file, and using the content-length (most servers should send that). That is unless we decide we want to automatically determine the length in seconds of episodes too, that would probably require downloading the whole file (or estimating, or hoping that the file has the correct id3 tags).

**Comment by t2t2** [comment]
Currently manually enterable, changing milestone to later improving
